# Generated by Django 5.0.2 on 2024-03-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=30, null=True)),
                ('Productqnt', models.IntegerField()),
                ('Unitoffprd', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
